dist: cosmic
language: bash

services:
- docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9112fb2807d4_key -iv $encrypted_9112fb2807d4_iv -in gcp-travis-bot-service-account-auth.json.enc -out gcp-travis-bot-service-account-auth.json -d

env:
  global:
    - GCP_REGION=europe-west2
    - PACKAGE_NAME=gcp-typescript-kata
    - secure: Fy4BhN5mwqFpV94ux9mgpzYI2Mb1rpvFPxg6hSPojMmN1f96UBcR3ItnM3d3WMqx5hLO7eX+pmoyVv9cp2AcpfzU/BUnF4sjR/apsoOZMF/4OPtcJVI8F7IWqs7Bz9DwnGxl8MeocZ+tVKaqvIY3CkxqXSzFjThFtSgKAGU2Hx7VV01AlrbrpUbXHJdE3Q3cVzyNztRt1H8RK9sok0PynXfEhwMinj2RVAELeXQ49Ay3+rabKpVnwd2r6ubWt0PjdzcW28UOIGheEDub91qcg/TJskFwT3A6mWRl/oFJr54eQa9cklN7A4uM4VEfvyhz4vtYUTJn06oGSXhZnoOfwJoopr1djO0EoQ8XAaLvFlCgGutQoSSdXhtWH8VQk7HSqGcU+D39u3ZIC5a4HLwdFisaLN/Hzo7zuBixknBpKN/PuqZOtAAw/0lryex+phYAUT0s9DoTA/iYq2+XL6zyo8J8xEzHxD09PEmpMO+JhVshQiWlSTq8w0SM4PeDL0NYFf6ATGvM1fahMzKGIkdyNJgQS6s5zMYa1tARTf5ofZUA5aMnpiBaMTrudi38sn85XIwQzrIUFfQJGpBafnopb3yAVFjnzXaHfQA83HnmpoRh4E+QTXTipoFMoAYDhl53zyDOJ8UpeR1BNVUhTNPlWzEgIXVhpbAGmSKS/5qITUU=
    - secure: X0K8UMbN2hXvZzqjoJyFvPOvqZLN/wTMCMAXp1mKrVT8jfMBCCHcVmQgDysG9hE3TfVk/QfU+uZRDfmVBhTonogYOMBSyMFFkUt0/TME1vhBVSt5LlGP8cYaD8tjyMk1Uwrzjwp9Ja+awLdqRJnf5mFPOTjukl6aHFscXVqoNEX1DjK1mM4l1Q+HQ9FPH0Hvy4RaBNZ3e6tEdgnY5BpLDR86REVd9lgTNUZfHW5s9p+UaB8PrcfKGgcvg3a6aT2I38eQamE9IlficC/FF791G+Yf9NmfujWvNS4xfr/+c4x+LzWv27a9mHbToUNL6hG2SEVAwuVbYbWMw9f6wd4remKhgVqLcL+kW8XiGGtoaD6ES6qpYxwZvhzPCZxVRrFn6K2OVnilQqhoxTIQLzwhe3dnuzdsu3AG5+AO23/2cThBPajbsJGG1Jzv4fE7rTDI6WD/UWh8TzsBwWhDza7c1PSuJpbibo4xUYUSa8Nczzm6dMKEjk6i9K6JR3vtp6Akglk4WMs+XuKwXCXsFPijLh0ZQJ633O1eyoucCMPu5zaAFkEJuggTJXUaKqkvtNXaf1ejfYsWvyGSciTCGKauTdmqX7uPc/xXBQrcx0Ylr9udzW7EAqZqxk9aKlNLmo1PaP/32JE7hp+2u0yDmNlwX00v7wMziwAJRAL3yidw1WA=

cache:
  directories:
    - /home/travis/.npm/
    - node_modules
    - gcp-typescript-kata-birthday.zip

jobs:
  include:
  - stage: build-infra
    name: "Build infrastructure Terraformation"
    script:
    - "./scripts/terraform-force-apply.sh account-wide"
  - stage: build
    name: "Build and Publish artifacts"
    script:
    - "./scripts/build.sh"
  - stage: deploy
    name: "Deploy to Dev"
    script:
    - "./scripts/terraform-plan.sh dev"
    - "./scripts/terraform-apply.sh dev"
